# Generated by Django 4.1.7 on 2023-03-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('create_all', models.BooleanField()),
                ('read_all', models.BooleanField()),
                ('update_all', models.BooleanField()),
                ('delete_all', models.BooleanField()),
                ('create_user', models.BooleanField()),
                ('read_user', models.BooleanField()),
                ('update_user', models.BooleanField()),
                ('delete_user', models.BooleanField()),
                ('create_event', models.BooleanField()),
                ('read_event', models.BooleanField()),
                ('update_event', models.BooleanField()),
                ('delete_event', models.BooleanField()),
                ('create_ticket', models.BooleanField()),
                ('read_ticket', models.BooleanField()),
                ('update_ticket', models.BooleanField()),
                ('delete_ticket', models.BooleanField()),
                ('create_volunteer', models.BooleanField()),
                ('read_volunteer', models.BooleanField()),
                ('update_volunteer', models.BooleanField()),
                ('delete_volunteer', models.BooleanField()),
                ('create_sales_n_report', models.BooleanField()),
                ('read_sales_n_report', models.BooleanField()),
                ('update_sales_n_report', models.BooleanField()),
                ('delete_sales_n_report', models.BooleanField()),
                ('create_email', models.BooleanField()),
                ('read_email', models.BooleanField()),
                ('update_email', models.BooleanField()),
                ('delete_email', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.permission')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user.role')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(max_length=200)),
                ('address_line_two', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('google_map_url', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
    ]
