# Generated by Django 4.1.7 on 2023-03-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='event_creator',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
