# Generated by Django 4.1.7 on 2023-03-02 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('preferred_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('fb_link', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('experience', models.CharField(max_length=200)),
                ('experience_description', models.CharField(max_length=2000)),
                ('current_job', models.CharField(max_length=200)),
                ('qualifications', models.CharField(max_length=200)),
                ('about', models.CharField(blank=True, max_length=2000, null=True)),
                ('comments', models.CharField(blank=True, max_length=2000, null=True)),
                ('preferred_tasks', models.CharField(max_length=200)),
                ('preferred_tasks_info', models.CharField(blank=True, max_length=2000, null=True)),
                ('preferred_time_frame', models.CharField(max_length=200)),
                ('volunteering_with_friends', models.CharField(blank=True, max_length=200, null=True)),
                ('volunteering_with_head', models.BooleanField(blank=True, null=True)),
                ('dept_head_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emg_first_name', models.CharField(max_length=200)),
                ('emg_last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emg_relation_name', models.CharField(max_length=200)),
                ('emg_phone', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
