# Generated by Django 4.1.7 on 2023-03-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0004_volunteerticket_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerStripePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('currency', models.CharField(default='aud', max_length=100)),
                ('volunteer_ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.volunteerticket')),
            ],
        ),
    ]
