# Generated by Django 4.1.7 on 2023-03-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerstripepayment',
            name='secret_key',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
