# Generated by Django 4.1.7 on 2023-03-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_volunteerstripepayment_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerstripepayment',
            name='secret_key',
        ),
    ]
