# Generated by Django 4.1.7 on 2023-03-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_volunteerstripepayment_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerstripepayment',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
