# Generated by Django 4.1.7 on 2023-03-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howmuchevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='howmuchevent',
            name='name',
        ),
        migrations.AddField(
            model_name='howmuchevent',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='howmuchevent',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
