# Generated by Django 4.1.7 on 2023-03-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_howmuchevent_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whereevent',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
