# Generated by Django 4.1.7 on 2023-03-18 01:17

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_whereevent_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whenevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='whenevent',
            name='name',
        ),
        migrations.AddField(
            model_name='whenevent',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='whenevent',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='whenevent',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='whenevent',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
