# Generated by Django 4.1.7 on 2023-03-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_whenevent_description_remove_whenevent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellingevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sellingevent',
            name='name',
        ),
        migrations.AddField(
            model_name='sellingevent',
            name='refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellingevent',
            name='refund_policy',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='sellingevent',
            name='refund_terms_n_conditions',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='sellingevent',
            name='stripe_payment',
            field=models.BooleanField(default=True),
        ),
    ]
