# Generated by Django 4.1.7 on 2023-03-18 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_sellingevent_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellingevent',
            old_name='refund_policy',
            new_name='policy',
        ),
        migrations.RenameField(
            model_name='sellingevent',
            old_name='refund_terms_n_conditions',
            new_name='terms_n_conditions',
        ),
    ]
