# Generated by Django 4.1.7 on 2023-03-12 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_volunteer_type', models.BooleanField(default=False)),
                ('discount_percent', models.IntegerField()),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agreement_template', models.CharField(max_length=100)),
                ('introduction_template', models.CharField(max_length=100)),
                ('whs_template', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('ticket_template', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.event')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.tickettype')),
            ],
        ),
    ]
