# Generated by Django 4.1.7 on 2023-03-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerticket',
            name='agreement_template',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='volunteerticket',
            name='introduction_template',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='volunteerticket',
            name='link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='volunteerticket',
            name='ticket_template',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='volunteerticket',
            name='whs_template',
            field=models.TextField(),
        ),
    ]
