# Generated by Django 4.1.7 on 2023-03-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerticket',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='volunteerticket',
            name='terms_n_condition',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='volunteerticket',
            name='agreement_template',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='volunteerticket',
            name='introduction_template',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='volunteerticket',
            name='ticket_template',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='volunteerticket',
            name='whs_template',
            field=models.TextField(default=''),
        ),
    ]
