# Generated by Django 4.1.7 on 2023-03-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_volunteerticket_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerticket',
            name='public_ket',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='volunteerticket',
            name='secret_key',
            field=models.TextField(default=''),
        ),
    ]
